import {MigrationInterface, QueryRunner} from "typeorm";

export class CreateDatabase1629501396295 implements MigrationInterface {
    name = 'CreateDatabase1629501396295'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "law" ("id" SERIAL NOT NULL, "url" character varying NOT NULL, "parentUrl" character varying, "title" character varying NOT NULL, "prefix" character varying, "htmlContent" character varying, "textContent" character varying NOT NULL, "contentHtmlSelector" character varying, "updateDiff" character varying, "published" boolean NOT NULL DEFAULT true, "esId" character varying, "tipo" character varying, "numero" character varying, "orgao" character varying, "dataPublicacao" date, "ementa" character varying, "slug" character varying NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "crawlerId" integer, CONSTRAINT "UQ_3d2424912150fc0260186b5002c" UNIQUE ("url"), CONSTRAINT "UQ_5f93d05583374423bfa7d4a31a1" UNIQUE ("slug"), CONSTRAINT "PK_5fb9289b907ae88d7f382e76793" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "jurisprudence" ("id" SERIAL NOT NULL, "url" character varying NOT NULL, "parentUrl" character varying, "titulo" character varying NOT NULL, "recursoNome" character varying NOT NULL, "htmlContent" character varying, "textContent" character varying NOT NULL, "contentHtmlSelector" character varying, "updateDiff" character varying, "published" boolean NOT NULL DEFAULT true, "esId" character varying, "tribunal" character varying, "siglaTribunal" character varying, "orgaoJulgador" character varying, "dataJulgamento" date, "dataPublicacao" date, "tipo" character varying, "classe" character varying, "codigoProcesso" character varying NOT NULL, "unidadeFederativa" character varying, "relator" character varying, "decisao" character varying, "ementa" character varying, "recorrente" character varying, "recorrido" character varying, "relatorio" character varying, "acordao" character varying, "juiz" character varying, "advogados" character varying, "advogadosReu" character varying, "slug" character varying NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "crawlerId" integer, CONSTRAINT "UQ_fc78ee8150633b24a5010a4737b" UNIQUE ("url"), CONSTRAINT "UQ_8898ee7ba252c5af73550f7b91e" UNIQUE ("codigoProcesso"), CONSTRAINT "UQ_0f6c42744159dfbeeb515c72b00" UNIQUE ("slug"), CONSTRAINT "PK_087bfb237144131df37761b72b0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "sub_category" ("id" SERIAL NOT NULL, "name" character varying NOT NULL, "slug" character varying NOT NULL, CONSTRAINT "UQ_f08643eb6693235bd717a56835e" UNIQUE ("slug"), CONSTRAINT "PK_59f4461923255f1ce7fc5e7423c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "crawler_update_time" ("id" SERIAL NOT NULL, "monday" boolean NOT NULL DEFAULT false, "tuesday" boolean NOT NULL DEFAULT false, "wednesday" boolean NOT NULL DEFAULT false, "thursday" boolean NOT NULL DEFAULT false, "friday" boolean NOT NULL DEFAULT false, "saturday" boolean NOT NULL DEFAULT false, "sunday" boolean NOT NULL DEFAULT false, "updateMondayTime" character varying, "updateTuesdayTime" character varying, "updateWednesdayTime" character varying, "updateThursdayTime" character varying, "updateFridayTime" character varying, "updateSaturdayTime" character varying, "updateSundayTime" character varying, CONSTRAINT "PK_8fe757ee665814141e35e729734" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "crawler_html_selector" ("id" SERIAL NOT NULL, "urlListEl" character varying, "titleEl" character varying, "alternativeTitleEl" character varying, "contentEl" character varying, "paginationEl" character varying, "nextPageEl" character varying, "previousPageEl" character varying, CONSTRAINT "PK_5bc9666b1f94993620119236da9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "crawler_type" ("id" SERIAL NOT NULL, "name" character varying NOT NULL, "functionName" character varying, "description" character varying NOT NULL, "params" json, CONSTRAINT "UQ_2c92a4d06572e183ac19cdd541d" UNIQUE ("name"), CONSTRAINT "PK_d485e84a0ee775146133a188405" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "crawler" ("id" SERIAL NOT NULL, "crawlerName" character varying NOT NULL, "baseUrl" character varying, "followOnlySameHost" boolean NOT NULL DEFAULT true, "updatedByBot" boolean NOT NULL DEFAULT false, "urlsToVisit" text, "logs" text, "urlsToVisitMongoId" character varying, "customCode" character varying NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "crawlerTypeId" integer, "updateTimeId" integer, "htmlSelectorsId" integer, CONSTRAINT "REL_9074e9e9c83075a84bce8e3a01" UNIQUE ("updateTimeId"), CONSTRAINT "REL_b3f6e62601cbc6af0a2c4e6127" UNIQUE ("htmlSelectorsId"), CONSTRAINT "PK_80a34e8da52ca526864c995e7a8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "federated_unit" ("id" SERIAL NOT NULL, "name" character varying NOT NULL, "slug" character varying NOT NULL, "description" character varying, "wiki" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_7c6d011bebfee95f4a6c24b7c3e" UNIQUE ("slug"), CONSTRAINT "PK_962205be5b60281c78e8c72ee19" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "category" ("id" SERIAL NOT NULL, "name" character varying NOT NULL, "slug" character varying NOT NULL, "description" character varying, "wiki" character varying, "order" integer, "featured" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_cb73208f151aa71cdd78f662d70" UNIQUE ("slug"), CONSTRAINT "PK_9c4e4a89e3674fc9f382d733f03" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "article" ("id" SERIAL NOT NULL, "title" character varying NOT NULL, "featured" boolean NOT NULL DEFAULT false, "summary" character varying, "imgCover" character varying, "content" character varying, "textContent" character varying, "published" boolean NOT NULL, "slug" character varying NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_0ab85f4be07b22d79906671d72f" UNIQUE ("slug"), CONSTRAINT "PK_40808690eb7b915046558c0f81b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "category_page" ("id" SERIAL NOT NULL, "title" character varying NOT NULL, "summary" character varying, "imgCover" character varying, "content" character varying, "textContent" character varying, "master" boolean NOT NULL DEFAULT false, "grid" boolean NOT NULL DEFAULT false, "published" boolean NOT NULL, "slug" character varying NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "parentId" integer, CONSTRAINT "UQ_8f932319db2967292eecd7b10c5" UNIQUE ("slug"), CONSTRAINT "PK_eb251641db02b0e80d232fd26d5" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "pagina_diario_oficial" ("id" SERIAL NOT NULL, "url" character varying NOT NULL, "dataPublicacao" date, "estado" character varying, "titulo" character varying NOT NULL, "htmlContent" character varying, "textContent" character varying NOT NULL, "published" boolean NOT NULL DEFAULT true, "esId" character varying, "tipo" character varying, "slug" character varying NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "parentId" integer, "crawlerId" integer, CONSTRAINT "UQ_1046e7991e61cebdf50537bf5eb" UNIQUE ("url"), CONSTRAINT "UQ_062cc862cc9104acf85355da533" UNIQUE ("slug"), CONSTRAINT "PK_af1a5e35e255dd3714ad364e29d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "diario_oficial" ("id" SERIAL NOT NULL, "url" character varying NOT NULL, "dataPublicacao" date, "estado" character varying, "titulo" character varying NOT NULL, "htmlContent" character varying, "textContent" character varying NOT NULL, "published" boolean NOT NULL DEFAULT true, "esId" character varying, "tipo" character varying, "slug" character varying NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "crawlerId" integer, CONSTRAINT "UQ_294117b97462a03c9a3df4af7ec" UNIQUE ("url"), CONSTRAINT "UQ_02b0e8a4e3dc0594cbb7302ca3a" UNIQUE ("slug"), CONSTRAINT "PK_a30153f84b72a4ed5eac8cd63a0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "user_role_enum" AS ENUM('admin', 'editor', 'guest', 'subscriber', 'personal', 'pro', 'premium', 'business', 'staff', 'free')`);
        await queryRunner.query(`CREATE TABLE "user" ("id" SERIAL NOT NULL, "name" character varying(255), "email" character varying(255) NOT NULL, "username" character varying(20), "profilePicture" character varying, "tokens" text, "admin" boolean NOT NULL DEFAULT false, "role" "user_role_enum" NOT NULL DEFAULT 'free', "google" character varying NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "expirationDate" TIMESTAMP DEFAULT now(), "escritorioAdministadorId" uuid, "escritorioSocioId" uuid, CONSTRAINT "UQ_e12875dfb3b1d92d7d7c5377e22" UNIQUE ("email"), CONSTRAINT "UQ_516c0d3ae599cb565cc3d9d6e07" UNIQUE ("google"), CONSTRAINT "REL_0c9919be86567e9edb3b0c96c7" UNIQUE ("escritorioAdministadorId"), CONSTRAINT "PK_cace4a159ff9f2512dd42373760" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "peticao" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "titulo" character varying NOT NULL, "slug" character varying NOT NULL, "content" character varying, "textContent" character varying, "header" character varying, "footer" character varying, "private" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "escritorioId" uuid, "processoId" uuid, "ownerId" integer, CONSTRAINT "UQ_6579d38e04facb342c9c734af2f" UNIQUE ("slug"), CONSTRAINT "PK_b305f34cad35c4193b9bd816e5b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "processo" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "nome" character varying NOT NULL, "slug" character varying NOT NULL, "andamento" character varying, "tri" character varying, "rg" character varying, "tituloEleitor" character varying, "carteiraMotorista" character varying, "endereco" character varying, "endereco2" character varying, "telefone" character varying, "telefone2" character varying, "email" character varying, "email2" character varying, "estadoCivil" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "escritorioId" uuid, CONSTRAINT "UQ_be44e7a00531d2a7c21be3fa42b" UNIQUE ("slug"), CONSTRAINT "PK_b72fde2a8acd7a422692b9ab5f4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "escritorio" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "nome" character varying NOT NULL, "slug" character varying NOT NULL, "descricao" character varying, "imgLogo" character varying, "ativo" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_efbb663dd38fae7d26896e536d2" UNIQUE ("slug"), CONSTRAINT "PK_2d1315cb36953e91c6fb1da04af" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "cliente" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "nome" character varying NOT NULL, "cpf" character varying, "rg" character varying, "tituloEleitor" character varying, "slug" character varying NOT NULL, "carteiraMotorista" character varying, "endereco" character varying, "endereco2" character varying, "telefone" character varying, "telefone2" character varying, "email" character varying, "email2" character varying, "estadoCivil" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "escritorioId" uuid, CONSTRAINT "UQ_e650671e66e79e24cb4b2df1cc5" UNIQUE ("slug"), CONSTRAINT "PK_18990e8df6cf7fe71b9dc0f5f39" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "peticao_previdenciarista" ("id" SERIAL NOT NULL, "titulo" character varying, "resumo" character varying, "tipo" character varying, "status" character varying, "sexo" character varying, "tipoDeProcesso" character varying, "tipoDeAcao" character varying, "tiposDeBeneficio" text array NOT NULL, "subtipo" text array NOT NULL, "competencia" character varying, "tempoDeContribuicaoMinimo" integer, "idadeMinima" integer, "periodo" character varying, "slug" character varying, "tags" text array NOT NULL, "conteudo" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_16c553d84ce2d650eb6d70e81b8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "law_categories_category" ("lawId" integer NOT NULL, "categoryId" integer NOT NULL, CONSTRAINT "PK_e2f29bfb17a6abf1a8f9a4b6d1c" PRIMARY KEY ("lawId", "categoryId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_7e7f5860b19c93de4d32c4990b" ON "law_categories_category" ("lawId") `);
        await queryRunner.query(`CREATE INDEX "IDX_29eabff1b9ddc1ddc5f18afc56" ON "law_categories_category" ("categoryId") `);
        await queryRunner.query(`CREATE TABLE "law_sub_categories_sub_category" ("lawId" integer NOT NULL, "subCategoryId" integer NOT NULL, CONSTRAINT "PK_20404def2ae2e4dc0843f102676" PRIMARY KEY ("lawId", "subCategoryId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_5551d2bb25742bc38e4947bc53" ON "law_sub_categories_sub_category" ("lawId") `);
        await queryRunner.query(`CREATE INDEX "IDX_a9abdd1a9571f8bd6f1bf42944" ON "law_sub_categories_sub_category" ("subCategoryId") `);
        await queryRunner.query(`CREATE TABLE "jurisprudence_categories_category" ("jurisprudenceId" integer NOT NULL, "categoryId" integer NOT NULL, CONSTRAINT "PK_cf5cf25cc37dfaab0797cacabcc" PRIMARY KEY ("jurisprudenceId", "categoryId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_2eaf9b811802a2c9225295dd59" ON "jurisprudence_categories_category" ("jurisprudenceId") `);
        await queryRunner.query(`CREATE INDEX "IDX_a068fb09c18d92c19ab2edb5ad" ON "jurisprudence_categories_category" ("categoryId") `);
        await queryRunner.query(`CREATE TABLE "jurisprudence_sub_categories_sub_category" ("jurisprudenceId" integer NOT NULL, "subCategoryId" integer NOT NULL, CONSTRAINT "PK_a0c0131054bf40c251de2f68d1f" PRIMARY KEY ("jurisprudenceId", "subCategoryId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_69f122b1a870a1e639e2f00475" ON "jurisprudence_sub_categories_sub_category" ("jurisprudenceId") `);
        await queryRunner.query(`CREATE INDEX "IDX_1716d2f91cf24ae666052217eb" ON "jurisprudence_sub_categories_sub_category" ("subCategoryId") `);
        await queryRunner.query(`CREATE TABLE "crawler_categories_category" ("crawlerId" integer NOT NULL, "categoryId" integer NOT NULL, CONSTRAINT "PK_a1e81c9daf3e3387e6e7f6d45b5" PRIMARY KEY ("crawlerId", "categoryId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_ba3281ee1651d69631dccd67a1" ON "crawler_categories_category" ("crawlerId") `);
        await queryRunner.query(`CREATE INDEX "IDX_a720b64c4e0e23daacc70bafb2" ON "crawler_categories_category" ("categoryId") `);
        await queryRunner.query(`CREATE TABLE "crawler_sub_categories_sub_category" ("crawlerId" integer NOT NULL, "subCategoryId" integer NOT NULL, CONSTRAINT "PK_52323c63997c7b94247ef3b9961" PRIMARY KEY ("crawlerId", "subCategoryId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_884855fa463afbe65e10f10639" ON "crawler_sub_categories_sub_category" ("crawlerId") `);
        await queryRunner.query(`CREATE INDEX "IDX_7e59af2495f4500d4d3732f174" ON "crawler_sub_categories_sub_category" ("subCategoryId") `);
        await queryRunner.query(`CREATE TABLE "federated_unit_categories_category" ("federatedUnitId" integer NOT NULL, "categoryId" integer NOT NULL, CONSTRAINT "PK_e86416715a92f70f7aee39fcc27" PRIMARY KEY ("federatedUnitId", "categoryId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_d29c281de5e2bb858b28de8366" ON "federated_unit_categories_category" ("federatedUnitId") `);
        await queryRunner.query(`CREATE INDEX "IDX_0d26c679511ebc8e5d8f4203a4" ON "federated_unit_categories_category" ("categoryId") `);
        await queryRunner.query(`CREATE TABLE "article_categories_category" ("articleId" integer NOT NULL, "categoryId" integer NOT NULL, CONSTRAINT "PK_a8116c8896d1d576d6ea7ad0d3c" PRIMARY KEY ("articleId", "categoryId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_4ba35bcb36b2715f61faa696c7" ON "article_categories_category" ("articleId") `);
        await queryRunner.query(`CREATE INDEX "IDX_5d9199768aa2bd9f91d175dc6d" ON "article_categories_category" ("categoryId") `);
        await queryRunner.query(`CREATE TABLE "article_sub_categories_sub_category" ("articleId" integer NOT NULL, "subCategoryId" integer NOT NULL, CONSTRAINT "PK_af390139e6dd4315acbfb6fba65" PRIMARY KEY ("articleId", "subCategoryId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_758d213154226f74ae86818aa8" ON "article_sub_categories_sub_category" ("articleId") `);
        await queryRunner.query(`CREATE INDEX "IDX_267ac3ce8a9ec9890d59c95f78" ON "article_sub_categories_sub_category" ("subCategoryId") `);
        await queryRunner.query(`CREATE TABLE "category_page_categories_category" ("categoryPageId" integer NOT NULL, "categoryId" integer NOT NULL, CONSTRAINT "PK_03497d494d2956ad2bbd3960333" PRIMARY KEY ("categoryPageId", "categoryId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_921fc6b8590a30eda721b457d0" ON "category_page_categories_category" ("categoryPageId") `);
        await queryRunner.query(`CREATE INDEX "IDX_21d6bb0f6f2052d63b48a07867" ON "category_page_categories_category" ("categoryId") `);
        await queryRunner.query(`CREATE TABLE "category_page_sub_categories_sub_category" ("categoryPageId" integer NOT NULL, "subCategoryId" integer NOT NULL, CONSTRAINT "PK_b2e2487243b509c1f1883d76299" PRIMARY KEY ("categoryPageId", "subCategoryId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_f05784bcef90de9624c93d1b18" ON "category_page_sub_categories_sub_category" ("categoryPageId") `);
        await queryRunner.query(`CREATE INDEX "IDX_63ab303e201ecacd335f5cd8e9" ON "category_page_sub_categories_sub_category" ("subCategoryId") `);
        await queryRunner.query(`CREATE TABLE "pagina_diario_oficial_categories_category" ("paginaDiarioOficialId" integer NOT NULL, "categoryId" integer NOT NULL, CONSTRAINT "PK_efa621471d157e2ac626f197099" PRIMARY KEY ("paginaDiarioOficialId", "categoryId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_07bd382caf0005715e731a85b6" ON "pagina_diario_oficial_categories_category" ("paginaDiarioOficialId") `);
        await queryRunner.query(`CREATE INDEX "IDX_72eb0ba330831d8ce7a003a751" ON "pagina_diario_oficial_categories_category" ("categoryId") `);
        await queryRunner.query(`CREATE TABLE "pagina_diario_oficial_sub_categories_sub_category" ("paginaDiarioOficialId" integer NOT NULL, "subCategoryId" integer NOT NULL, CONSTRAINT "PK_cfad782f44d4c69a764d0f108f2" PRIMARY KEY ("paginaDiarioOficialId", "subCategoryId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_a14fa3b3ad31e60a5e2dc0b32b" ON "pagina_diario_oficial_sub_categories_sub_category" ("paginaDiarioOficialId") `);
        await queryRunner.query(`CREATE INDEX "IDX_2b55c02ea1f95f6aba382227cf" ON "pagina_diario_oficial_sub_categories_sub_category" ("subCategoryId") `);
        await queryRunner.query(`CREATE TABLE "diario_oficial_categories_category" ("diarioOficialId" integer NOT NULL, "categoryId" integer NOT NULL, CONSTRAINT "PK_85d510e7a0f0e4d8fdb476e54ea" PRIMARY KEY ("diarioOficialId", "categoryId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_3d7207dc5d93b1e8f8cc1ac34c" ON "diario_oficial_categories_category" ("diarioOficialId") `);
        await queryRunner.query(`CREATE INDEX "IDX_5d5692a81d0aa6e2b2a4c501fa" ON "diario_oficial_categories_category" ("categoryId") `);
        await queryRunner.query(`CREATE TABLE "diario_oficial_sub_categories_sub_category" ("diarioOficialId" integer NOT NULL, "subCategoryId" integer NOT NULL, CONSTRAINT "PK_80370693ab0d41597f93f55e062" PRIMARY KEY ("diarioOficialId", "subCategoryId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_0d8a506055cd124fe5adb17e20" ON "diario_oficial_sub_categories_sub_category" ("diarioOficialId") `);
        await queryRunner.query(`CREATE INDEX "IDX_0f02729944f9f9936acebcd018" ON "diario_oficial_sub_categories_sub_category" ("subCategoryId") `);
        await queryRunner.query(`CREATE TABLE "peticao_allow_access_to_user" ("peticaoId" uuid NOT NULL, "userId" integer NOT NULL, CONSTRAINT "PK_3e8d96f795ce2aa5f34695da925" PRIMARY KEY ("peticaoId", "userId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_71a94dc010374f8965e4be5f42" ON "peticao_allow_access_to_user" ("peticaoId") `);
        await queryRunner.query(`CREATE INDEX "IDX_39bc1ec6b510d1ef9bc9c2e3d5" ON "peticao_allow_access_to_user" ("userId") `);
        await queryRunner.query(`CREATE TABLE "processo_clientes_cliente" ("processoId" uuid NOT NULL, "clienteId" uuid NOT NULL, CONSTRAINT "PK_952f9fd4763443783e64960a17c" PRIMARY KEY ("processoId", "clienteId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_2d20da1d2732772ff92a523c14" ON "processo_clientes_cliente" ("processoId") `);
        await queryRunner.query(`CREATE INDEX "IDX_bcb7fc0fa189cce9ea44419a2a" ON "processo_clientes_cliente" ("clienteId") `);
        await queryRunner.query(`ALTER TABLE "law" ADD CONSTRAINT "FK_1553ec5fce9002d7c26965a35d0" FOREIGN KEY ("crawlerId") REFERENCES "crawler"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "jurisprudence" ADD CONSTRAINT "FK_817f19bfb26236c8300ea3dae4b" FOREIGN KEY ("crawlerId") REFERENCES "crawler"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "crawler" ADD CONSTRAINT "FK_ef26f1cf8fe4716dcd7ceff2306" FOREIGN KEY ("crawlerTypeId") REFERENCES "crawler_type"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "crawler" ADD CONSTRAINT "FK_9074e9e9c83075a84bce8e3a019" FOREIGN KEY ("updateTimeId") REFERENCES "crawler_update_time"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "crawler" ADD CONSTRAINT "FK_b3f6e62601cbc6af0a2c4e61277" FOREIGN KEY ("htmlSelectorsId") REFERENCES "crawler_html_selector"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "category_page" ADD CONSTRAINT "FK_b8079881958b4f886fb2c318bab" FOREIGN KEY ("parentId") REFERENCES "category_page"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pagina_diario_oficial" ADD CONSTRAINT "FK_7cfa2c9cc9ad47c0f889e7c616d" FOREIGN KEY ("parentId") REFERENCES "diario_oficial"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pagina_diario_oficial" ADD CONSTRAINT "FK_2a2e7fd669df502ea8c1b3c5d5b" FOREIGN KEY ("crawlerId") REFERENCES "crawler"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "diario_oficial" ADD CONSTRAINT "FK_91720d1756e1d171b53af06ac4c" FOREIGN KEY ("crawlerId") REFERENCES "crawler"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user" ADD CONSTRAINT "FK_0c9919be86567e9edb3b0c96c70" FOREIGN KEY ("escritorioAdministadorId") REFERENCES "escritorio"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user" ADD CONSTRAINT "FK_c156fffa69831a1efc208c97ea5" FOREIGN KEY ("escritorioSocioId") REFERENCES "escritorio"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "peticao" ADD CONSTRAINT "FK_2438ad7395a316e382522f29ee4" FOREIGN KEY ("escritorioId") REFERENCES "escritorio"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "peticao" ADD CONSTRAINT "FK_06f32b385db2b2cfc63acf12bc0" FOREIGN KEY ("processoId") REFERENCES "processo"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "peticao" ADD CONSTRAINT "FK_5abe344cb2797429d2cfd537241" FOREIGN KEY ("ownerId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "processo" ADD CONSTRAINT "FK_1a85be99fe722a1c458a309da7a" FOREIGN KEY ("escritorioId") REFERENCES "escritorio"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cliente" ADD CONSTRAINT "FK_4b2586a4339ea367efc0ba7396f" FOREIGN KEY ("escritorioId") REFERENCES "escritorio"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "law_categories_category" ADD CONSTRAINT "FK_7e7f5860b19c93de4d32c4990b6" FOREIGN KEY ("lawId") REFERENCES "law"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "law_categories_category" ADD CONSTRAINT "FK_29eabff1b9ddc1ddc5f18afc567" FOREIGN KEY ("categoryId") REFERENCES "category"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "law_sub_categories_sub_category" ADD CONSTRAINT "FK_5551d2bb25742bc38e4947bc539" FOREIGN KEY ("lawId") REFERENCES "law"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "law_sub_categories_sub_category" ADD CONSTRAINT "FK_a9abdd1a9571f8bd6f1bf429448" FOREIGN KEY ("subCategoryId") REFERENCES "sub_category"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "jurisprudence_categories_category" ADD CONSTRAINT "FK_2eaf9b811802a2c9225295dd591" FOREIGN KEY ("jurisprudenceId") REFERENCES "jurisprudence"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "jurisprudence_categories_category" ADD CONSTRAINT "FK_a068fb09c18d92c19ab2edb5ade" FOREIGN KEY ("categoryId") REFERENCES "category"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "jurisprudence_sub_categories_sub_category" ADD CONSTRAINT "FK_69f122b1a870a1e639e2f00475f" FOREIGN KEY ("jurisprudenceId") REFERENCES "jurisprudence"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "jurisprudence_sub_categories_sub_category" ADD CONSTRAINT "FK_1716d2f91cf24ae666052217eb8" FOREIGN KEY ("subCategoryId") REFERENCES "sub_category"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "crawler_categories_category" ADD CONSTRAINT "FK_ba3281ee1651d69631dccd67a13" FOREIGN KEY ("crawlerId") REFERENCES "crawler"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "crawler_categories_category" ADD CONSTRAINT "FK_a720b64c4e0e23daacc70bafb2c" FOREIGN KEY ("categoryId") REFERENCES "category"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "crawler_sub_categories_sub_category" ADD CONSTRAINT "FK_884855fa463afbe65e10f106394" FOREIGN KEY ("crawlerId") REFERENCES "crawler"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "crawler_sub_categories_sub_category" ADD CONSTRAINT "FK_7e59af2495f4500d4d3732f174d" FOREIGN KEY ("subCategoryId") REFERENCES "sub_category"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "federated_unit_categories_category" ADD CONSTRAINT "FK_d29c281de5e2bb858b28de83666" FOREIGN KEY ("federatedUnitId") REFERENCES "federated_unit"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "federated_unit_categories_category" ADD CONSTRAINT "FK_0d26c679511ebc8e5d8f4203a42" FOREIGN KEY ("categoryId") REFERENCES "category"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "article_categories_category" ADD CONSTRAINT "FK_4ba35bcb36b2715f61faa696c7e" FOREIGN KEY ("articleId") REFERENCES "article"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "article_categories_category" ADD CONSTRAINT "FK_5d9199768aa2bd9f91d175dc6d1" FOREIGN KEY ("categoryId") REFERENCES "category"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "article_sub_categories_sub_category" ADD CONSTRAINT "FK_758d213154226f74ae86818aa86" FOREIGN KEY ("articleId") REFERENCES "article"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "article_sub_categories_sub_category" ADD CONSTRAINT "FK_267ac3ce8a9ec9890d59c95f789" FOREIGN KEY ("subCategoryId") REFERENCES "sub_category"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "category_page_categories_category" ADD CONSTRAINT "FK_921fc6b8590a30eda721b457d0d" FOREIGN KEY ("categoryPageId") REFERENCES "category_page"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "category_page_categories_category" ADD CONSTRAINT "FK_21d6bb0f6f2052d63b48a078671" FOREIGN KEY ("categoryId") REFERENCES "category"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "category_page_sub_categories_sub_category" ADD CONSTRAINT "FK_f05784bcef90de9624c93d1b183" FOREIGN KEY ("categoryPageId") REFERENCES "category_page"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "category_page_sub_categories_sub_category" ADD CONSTRAINT "FK_63ab303e201ecacd335f5cd8e9b" FOREIGN KEY ("subCategoryId") REFERENCES "sub_category"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pagina_diario_oficial_categories_category" ADD CONSTRAINT "FK_07bd382caf0005715e731a85b63" FOREIGN KEY ("paginaDiarioOficialId") REFERENCES "pagina_diario_oficial"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pagina_diario_oficial_categories_category" ADD CONSTRAINT "FK_72eb0ba330831d8ce7a003a751b" FOREIGN KEY ("categoryId") REFERENCES "category"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pagina_diario_oficial_sub_categories_sub_category" ADD CONSTRAINT "FK_a14fa3b3ad31e60a5e2dc0b32bb" FOREIGN KEY ("paginaDiarioOficialId") REFERENCES "pagina_diario_oficial"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pagina_diario_oficial_sub_categories_sub_category" ADD CONSTRAINT "FK_2b55c02ea1f95f6aba382227cf2" FOREIGN KEY ("subCategoryId") REFERENCES "sub_category"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "diario_oficial_categories_category" ADD CONSTRAINT "FK_3d7207dc5d93b1e8f8cc1ac34c9" FOREIGN KEY ("diarioOficialId") REFERENCES "diario_oficial"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "diario_oficial_categories_category" ADD CONSTRAINT "FK_5d5692a81d0aa6e2b2a4c501fa4" FOREIGN KEY ("categoryId") REFERENCES "category"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "diario_oficial_sub_categories_sub_category" ADD CONSTRAINT "FK_0d8a506055cd124fe5adb17e202" FOREIGN KEY ("diarioOficialId") REFERENCES "diario_oficial"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "diario_oficial_sub_categories_sub_category" ADD CONSTRAINT "FK_0f02729944f9f9936acebcd018e" FOREIGN KEY ("subCategoryId") REFERENCES "sub_category"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "peticao_allow_access_to_user" ADD CONSTRAINT "FK_71a94dc010374f8965e4be5f422" FOREIGN KEY ("peticaoId") REFERENCES "peticao"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "peticao_allow_access_to_user" ADD CONSTRAINT "FK_39bc1ec6b510d1ef9bc9c2e3d5a" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "processo_clientes_cliente" ADD CONSTRAINT "FK_2d20da1d2732772ff92a523c14a" FOREIGN KEY ("processoId") REFERENCES "processo"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "processo_clientes_cliente" ADD CONSTRAINT "FK_bcb7fc0fa189cce9ea44419a2a0" FOREIGN KEY ("clienteId") REFERENCES "cliente"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "processo_clientes_cliente" DROP CONSTRAINT "FK_bcb7fc0fa189cce9ea44419a2a0"`);
        await queryRunner.query(`ALTER TABLE "processo_clientes_cliente" DROP CONSTRAINT "FK_2d20da1d2732772ff92a523c14a"`);
        await queryRunner.query(`ALTER TABLE "peticao_allow_access_to_user" DROP CONSTRAINT "FK_39bc1ec6b510d1ef9bc9c2e3d5a"`);
        await queryRunner.query(`ALTER TABLE "peticao_allow_access_to_user" DROP CONSTRAINT "FK_71a94dc010374f8965e4be5f422"`);
        await queryRunner.query(`ALTER TABLE "diario_oficial_sub_categories_sub_category" DROP CONSTRAINT "FK_0f02729944f9f9936acebcd018e"`);
        await queryRunner.query(`ALTER TABLE "diario_oficial_sub_categories_sub_category" DROP CONSTRAINT "FK_0d8a506055cd124fe5adb17e202"`);
        await queryRunner.query(`ALTER TABLE "diario_oficial_categories_category" DROP CONSTRAINT "FK_5d5692a81d0aa6e2b2a4c501fa4"`);
        await queryRunner.query(`ALTER TABLE "diario_oficial_categories_category" DROP CONSTRAINT "FK_3d7207dc5d93b1e8f8cc1ac34c9"`);
        await queryRunner.query(`ALTER TABLE "pagina_diario_oficial_sub_categories_sub_category" DROP CONSTRAINT "FK_2b55c02ea1f95f6aba382227cf2"`);
        await queryRunner.query(`ALTER TABLE "pagina_diario_oficial_sub_categories_sub_category" DROP CONSTRAINT "FK_a14fa3b3ad31e60a5e2dc0b32bb"`);
        await queryRunner.query(`ALTER TABLE "pagina_diario_oficial_categories_category" DROP CONSTRAINT "FK_72eb0ba330831d8ce7a003a751b"`);
        await queryRunner.query(`ALTER TABLE "pagina_diario_oficial_categories_category" DROP CONSTRAINT "FK_07bd382caf0005715e731a85b63"`);
        await queryRunner.query(`ALTER TABLE "category_page_sub_categories_sub_category" DROP CONSTRAINT "FK_63ab303e201ecacd335f5cd8e9b"`);
        await queryRunner.query(`ALTER TABLE "category_page_sub_categories_sub_category" DROP CONSTRAINT "FK_f05784bcef90de9624c93d1b183"`);
        await queryRunner.query(`ALTER TABLE "category_page_categories_category" DROP CONSTRAINT "FK_21d6bb0f6f2052d63b48a078671"`);
        await queryRunner.query(`ALTER TABLE "category_page_categories_category" DROP CONSTRAINT "FK_921fc6b8590a30eda721b457d0d"`);
        await queryRunner.query(`ALTER TABLE "article_sub_categories_sub_category" DROP CONSTRAINT "FK_267ac3ce8a9ec9890d59c95f789"`);
        await queryRunner.query(`ALTER TABLE "article_sub_categories_sub_category" DROP CONSTRAINT "FK_758d213154226f74ae86818aa86"`);
        await queryRunner.query(`ALTER TABLE "article_categories_category" DROP CONSTRAINT "FK_5d9199768aa2bd9f91d175dc6d1"`);
        await queryRunner.query(`ALTER TABLE "article_categories_category" DROP CONSTRAINT "FK_4ba35bcb36b2715f61faa696c7e"`);
        await queryRunner.query(`ALTER TABLE "federated_unit_categories_category" DROP CONSTRAINT "FK_0d26c679511ebc8e5d8f4203a42"`);
        await queryRunner.query(`ALTER TABLE "federated_unit_categories_category" DROP CONSTRAINT "FK_d29c281de5e2bb858b28de83666"`);
        await queryRunner.query(`ALTER TABLE "crawler_sub_categories_sub_category" DROP CONSTRAINT "FK_7e59af2495f4500d4d3732f174d"`);
        await queryRunner.query(`ALTER TABLE "crawler_sub_categories_sub_category" DROP CONSTRAINT "FK_884855fa463afbe65e10f106394"`);
        await queryRunner.query(`ALTER TABLE "crawler_categories_category" DROP CONSTRAINT "FK_a720b64c4e0e23daacc70bafb2c"`);
        await queryRunner.query(`ALTER TABLE "crawler_categories_category" DROP CONSTRAINT "FK_ba3281ee1651d69631dccd67a13"`);
        await queryRunner.query(`ALTER TABLE "jurisprudence_sub_categories_sub_category" DROP CONSTRAINT "FK_1716d2f91cf24ae666052217eb8"`);
        await queryRunner.query(`ALTER TABLE "jurisprudence_sub_categories_sub_category" DROP CONSTRAINT "FK_69f122b1a870a1e639e2f00475f"`);
        await queryRunner.query(`ALTER TABLE "jurisprudence_categories_category" DROP CONSTRAINT "FK_a068fb09c18d92c19ab2edb5ade"`);
        await queryRunner.query(`ALTER TABLE "jurisprudence_categories_category" DROP CONSTRAINT "FK_2eaf9b811802a2c9225295dd591"`);
        await queryRunner.query(`ALTER TABLE "law_sub_categories_sub_category" DROP CONSTRAINT "FK_a9abdd1a9571f8bd6f1bf429448"`);
        await queryRunner.query(`ALTER TABLE "law_sub_categories_sub_category" DROP CONSTRAINT "FK_5551d2bb25742bc38e4947bc539"`);
        await queryRunner.query(`ALTER TABLE "law_categories_category" DROP CONSTRAINT "FK_29eabff1b9ddc1ddc5f18afc567"`);
        await queryRunner.query(`ALTER TABLE "law_categories_category" DROP CONSTRAINT "FK_7e7f5860b19c93de4d32c4990b6"`);
        await queryRunner.query(`ALTER TABLE "cliente" DROP CONSTRAINT "FK_4b2586a4339ea367efc0ba7396f"`);
        await queryRunner.query(`ALTER TABLE "processo" DROP CONSTRAINT "FK_1a85be99fe722a1c458a309da7a"`);
        await queryRunner.query(`ALTER TABLE "peticao" DROP CONSTRAINT "FK_5abe344cb2797429d2cfd537241"`);
        await queryRunner.query(`ALTER TABLE "peticao" DROP CONSTRAINT "FK_06f32b385db2b2cfc63acf12bc0"`);
        await queryRunner.query(`ALTER TABLE "peticao" DROP CONSTRAINT "FK_2438ad7395a316e382522f29ee4"`);
        await queryRunner.query(`ALTER TABLE "user" DROP CONSTRAINT "FK_c156fffa69831a1efc208c97ea5"`);
        await queryRunner.query(`ALTER TABLE "user" DROP CONSTRAINT "FK_0c9919be86567e9edb3b0c96c70"`);
        await queryRunner.query(`ALTER TABLE "diario_oficial" DROP CONSTRAINT "FK_91720d1756e1d171b53af06ac4c"`);
        await queryRunner.query(`ALTER TABLE "pagina_diario_oficial" DROP CONSTRAINT "FK_2a2e7fd669df502ea8c1b3c5d5b"`);
        await queryRunner.query(`ALTER TABLE "pagina_diario_oficial" DROP CONSTRAINT "FK_7cfa2c9cc9ad47c0f889e7c616d"`);
        await queryRunner.query(`ALTER TABLE "category_page" DROP CONSTRAINT "FK_b8079881958b4f886fb2c318bab"`);
        await queryRunner.query(`ALTER TABLE "crawler" DROP CONSTRAINT "FK_b3f6e62601cbc6af0a2c4e61277"`);
        await queryRunner.query(`ALTER TABLE "crawler" DROP CONSTRAINT "FK_9074e9e9c83075a84bce8e3a019"`);
        await queryRunner.query(`ALTER TABLE "crawler" DROP CONSTRAINT "FK_ef26f1cf8fe4716dcd7ceff2306"`);
        await queryRunner.query(`ALTER TABLE "jurisprudence" DROP CONSTRAINT "FK_817f19bfb26236c8300ea3dae4b"`);
        await queryRunner.query(`ALTER TABLE "law" DROP CONSTRAINT "FK_1553ec5fce9002d7c26965a35d0"`);
        await queryRunner.query(`DROP INDEX "IDX_bcb7fc0fa189cce9ea44419a2a"`);
        await queryRunner.query(`DROP INDEX "IDX_2d20da1d2732772ff92a523c14"`);
        await queryRunner.query(`DROP TABLE "processo_clientes_cliente"`);
        await queryRunner.query(`DROP INDEX "IDX_39bc1ec6b510d1ef9bc9c2e3d5"`);
        await queryRunner.query(`DROP INDEX "IDX_71a94dc010374f8965e4be5f42"`);
        await queryRunner.query(`DROP TABLE "peticao_allow_access_to_user"`);
        await queryRunner.query(`DROP INDEX "IDX_0f02729944f9f9936acebcd018"`);
        await queryRunner.query(`DROP INDEX "IDX_0d8a506055cd124fe5adb17e20"`);
        await queryRunner.query(`DROP TABLE "diario_oficial_sub_categories_sub_category"`);
        await queryRunner.query(`DROP INDEX "IDX_5d5692a81d0aa6e2b2a4c501fa"`);
        await queryRunner.query(`DROP INDEX "IDX_3d7207dc5d93b1e8f8cc1ac34c"`);
        await queryRunner.query(`DROP TABLE "diario_oficial_categories_category"`);
        await queryRunner.query(`DROP INDEX "IDX_2b55c02ea1f95f6aba382227cf"`);
        await queryRunner.query(`DROP INDEX "IDX_a14fa3b3ad31e60a5e2dc0b32b"`);
        await queryRunner.query(`DROP TABLE "pagina_diario_oficial_sub_categories_sub_category"`);
        await queryRunner.query(`DROP INDEX "IDX_72eb0ba330831d8ce7a003a751"`);
        await queryRunner.query(`DROP INDEX "IDX_07bd382caf0005715e731a85b6"`);
        await queryRunner.query(`DROP TABLE "pagina_diario_oficial_categories_category"`);
        await queryRunner.query(`DROP INDEX "IDX_63ab303e201ecacd335f5cd8e9"`);
        await queryRunner.query(`DROP INDEX "IDX_f05784bcef90de9624c93d1b18"`);
        await queryRunner.query(`DROP TABLE "category_page_sub_categories_sub_category"`);
        await queryRunner.query(`DROP INDEX "IDX_21d6bb0f6f2052d63b48a07867"`);
        await queryRunner.query(`DROP INDEX "IDX_921fc6b8590a30eda721b457d0"`);
        await queryRunner.query(`DROP TABLE "category_page_categories_category"`);
        await queryRunner.query(`DROP INDEX "IDX_267ac3ce8a9ec9890d59c95f78"`);
        await queryRunner.query(`DROP INDEX "IDX_758d213154226f74ae86818aa8"`);
        await queryRunner.query(`DROP TABLE "article_sub_categories_sub_category"`);
        await queryRunner.query(`DROP INDEX "IDX_5d9199768aa2bd9f91d175dc6d"`);
        await queryRunner.query(`DROP INDEX "IDX_4ba35bcb36b2715f61faa696c7"`);
        await queryRunner.query(`DROP TABLE "article_categories_category"`);
        await queryRunner.query(`DROP INDEX "IDX_0d26c679511ebc8e5d8f4203a4"`);
        await queryRunner.query(`DROP INDEX "IDX_d29c281de5e2bb858b28de8366"`);
        await queryRunner.query(`DROP TABLE "federated_unit_categories_category"`);
        await queryRunner.query(`DROP INDEX "IDX_7e59af2495f4500d4d3732f174"`);
        await queryRunner.query(`DROP INDEX "IDX_884855fa463afbe65e10f10639"`);
        await queryRunner.query(`DROP TABLE "crawler_sub_categories_sub_category"`);
        await queryRunner.query(`DROP INDEX "IDX_a720b64c4e0e23daacc70bafb2"`);
        await queryRunner.query(`DROP INDEX "IDX_ba3281ee1651d69631dccd67a1"`);
        await queryRunner.query(`DROP TABLE "crawler_categories_category"`);
        await queryRunner.query(`DROP INDEX "IDX_1716d2f91cf24ae666052217eb"`);
        await queryRunner.query(`DROP INDEX "IDX_69f122b1a870a1e639e2f00475"`);
        await queryRunner.query(`DROP TABLE "jurisprudence_sub_categories_sub_category"`);
        await queryRunner.query(`DROP INDEX "IDX_a068fb09c18d92c19ab2edb5ad"`);
        await queryRunner.query(`DROP INDEX "IDX_2eaf9b811802a2c9225295dd59"`);
        await queryRunner.query(`DROP TABLE "jurisprudence_categories_category"`);
        await queryRunner.query(`DROP INDEX "IDX_a9abdd1a9571f8bd6f1bf42944"`);
        await queryRunner.query(`DROP INDEX "IDX_5551d2bb25742bc38e4947bc53"`);
        await queryRunner.query(`DROP TABLE "law_sub_categories_sub_category"`);
        await queryRunner.query(`DROP INDEX "IDX_29eabff1b9ddc1ddc5f18afc56"`);
        await queryRunner.query(`DROP INDEX "IDX_7e7f5860b19c93de4d32c4990b"`);
        await queryRunner.query(`DROP TABLE "law_categories_category"`);
        await queryRunner.query(`DROP TABLE "peticao_previdenciarista"`);
        await queryRunner.query(`DROP TABLE "cliente"`);
        await queryRunner.query(`DROP TABLE "escritorio"`);
        await queryRunner.query(`DROP TABLE "processo"`);
        await queryRunner.query(`DROP TABLE "peticao"`);
        await queryRunner.query(`DROP TABLE "user"`);
        await queryRunner.query(`DROP TYPE "user_role_enum"`);
        await queryRunner.query(`DROP TABLE "diario_oficial"`);
        await queryRunner.query(`DROP TABLE "pagina_diario_oficial"`);
        await queryRunner.query(`DROP TABLE "category_page"`);
        await queryRunner.query(`DROP TABLE "article"`);
        await queryRunner.query(`DROP TABLE "category"`);
        await queryRunner.query(`DROP TABLE "federated_unit"`);
        await queryRunner.query(`DROP TABLE "crawler"`);
        await queryRunner.query(`DROP TABLE "crawler_type"`);
        await queryRunner.query(`DROP TABLE "crawler_html_selector"`);
        await queryRunner.query(`DROP TABLE "crawler_update_time"`);
        await queryRunner.query(`DROP TABLE "sub_category"`);
        await queryRunner.query(`DROP TABLE "jurisprudence"`);
        await queryRunner.query(`DROP TABLE "law"`);
    }

}
