const ptBR = window.tinymce.addI18n('pt_BR', {
  Redo: 'Refazer',
  Undo: 'Desfazer',
  Cut: 'Cortar',
  Copy: 'Copiar',
  Paste: 'Colar',
  'Select all': 'Selecionar tudo',
  'New document': 'Novo documento',
  Ok: 'Ok',
  Cancel: 'Cancelar',
  'Visual aids': 'Ajuda visual',
  Bold: 'Negrito',
  Italic: 'It\u00E1lico',
  Underline: 'Sublinhado',
  Strikethrough: 'Tachado',
  Superscript: 'Sobrescrito',
  Subscript: 'Subscrito',
  'Clear formatting': 'Limpar formata\u00E7\u00E3o',
  'Align left': 'Alinhar \u00E0 esquerda',
  'Align center': 'Centralizar',
  'Align right': 'Alinhar \u00E0 direita',
  Justify: 'Justificar',
  'Bullet list': 'Lista n\u00E3o ordenada',
  'Numbered list': 'Lista ordenada',
  'Decrease indent': 'Diminuir recuo',
  'Increase indent': 'Aumentar recuo',
  Close: 'Fechar',
  Formats: 'Formatos',
  "Your browser doesn't support direct access to the clipboard. Please use the Ctrl+X/C/V keyboard shortcuts instead.":
    'Seu navegador n\u00E3o suporta acesso direto \u00E0 \u00E1rea de transfer\u00EAncia. Por favor use os atalhos Ctrl+X - C - V do teclado',
  Headers: 'Cabe\u00E7alhos',
  'Header 1': 'Cabe\u00E7alho 1',
  'Header 2': 'Cabe\u00E7alho 2',
  'Header 3': 'Cabe\u00E7alho 3',
  'Header 4': 'Cabe\u00E7alho 4',
  'Header 5': 'Cabe\u00E7alho 5',
  'Header 6': 'Cabe\u00E7alho 6',
  Headings: 'T\u00EDtulos',
  'Heading 1': 'T\u00EDtulo 1',
  'Heading 2': 'T\u00EDtulo 2',
  'Heading 3': 'T\u00EDtulo 3',
  'Heading 4': 'T\u00EDtulo 4',
  'Heading 5': 'T\u00EDtulo 5',
  'Heading 6': 'T\u00EDtulo 6',
  Preformatted: 'Pr\u00E9-formatado',
  Div: 'Div',
  Pre: 'Pre',
  Code: 'C\u00F3digo',
  Paragraph: 'Par\u00E1grafo',
  Blockquote: 'Aspas',
  Inline: 'Em linha',
  Blocks: 'Blocos',
  'Paste is now in plain text mode. Contents will now be pasted as plain text until you toggle this option off.':
    'O comando colar est\u00E1 agora em modo texto plano. O conte\u00FAdo ser\u00E1 colado como texto plano at\u00E9 voc\u00EA desligar esta op\u00E7\u00E3o.',
  Fonts: 'Fontes',
  'Font Sizes': 'Tamanhos da fonte',
  Class: 'Classe',
  'Browse for an image': 'Procure uma imagem',
  OR: 'OU',
  'Drop an image here': 'Solte uma imagem aqui',
  Upload: 'Carregar',
  Block: 'Bloco',
  Align: 'Alinhamento',
  Default: 'Padr\u00E3o',
  Circle: 'C\u00EDrculo',
  Disc: 'Disco',
  Square: 'Quadrado',
  'Lower Alpha': 'a. b. c. ...',
  'Lower Greek': '\u03B1. \u03B2. \u03B3. ...',
  'Lower Roman': 'i. ii. iii. ...',
  'Upper Alpha': 'A. B. C. ...',
  'Upper Roman': 'I. II. III. ...',
  'Anchor...': '\u00C2ncora...',
  Name: 'Nome',
  Id: 'Id',
  'Id should start with a letter, followed only by letters, numbers, dashes, dots, colons or underscores.':
    'Id deve come\u00E7ar com uma letra, seguido apenas por letras, n\u00FAmeros, tra\u00E7os, pontos, dois pontos ou sublinhados.',
  'You have unsaved changes are you sure you want to navigate away?':
    'Voc\u00EA tem mudan\u00E7as n\u00E3o salvas. Voc\u00EA tem certeza que deseja sair?',
  'Restore last draft': 'Restaurar \u00FAltimo rascunho',
  'Special character...': 'Caractere especial...',
  'Source code': 'C\u00F3digo fonte',
  'Insert/Edit code sample': 'Inserir/Editar c\u00F3digo de exemplo',
  Language: 'Idioma',
  'Code sample...': 'Exemplo de c\u00F3digo...',
  'Color Picker': 'Seletor de Cores',
  R: 'R',
  G: 'G',
  B: 'B',
  'Left to right': 'Da esquerda para a direita',
  'Right to left': 'Da direita para a esquerda',
  'Emoticons...': 'Emojis...',
  'Metadata and Document Properties': 'Metadados e Propriedades do Documento',
  Title: 'T\u00EDtulo',
  Keywords: 'Palavras-chave',
  Description: 'Descri\u00E7\u00E3o',
  Robots: 'Rob\u00F4s',
  Author: 'Autor',
  Encoding: 'Codifica\u00E7\u00E3o',
  Fullscreen: 'Tela cheia',
  Action: 'A\u00E7\u00E3o',
  Shortcut: 'Atalho',
  Help: 'Ajuda',
  Address: 'Endere\u00E7o',
  'Focus to menubar': 'Foco no menu',
  'Focus to toolbar': 'Foco na barra de ferramentas',
  'Focus to element path': 'Foco no caminho do elemento',
  'Focus to contextual toolbar': 'Foco na barra de ferramentas contextual',
  'Insert link (if link plugin activated)':
    'Inserir link (se o plugin de link estiver ativado)',
  'Save (if save plugin activated)':
    'Salvar (se o plugin de salvar estiver ativado)',
  'Find (if searchreplace plugin activated)':
    'Procurar (se o plugin de procurar e substituir estiver ativado)',
  'Plugins installed ({0}):': 'Plugins instalados ({0}):',
  'Premium plugins:': 'Plugins premium:',
  'Learn more...': 'Saiba mais...',
  'You are using {0}': 'Voc\u00EA est\u00E1 usando {0}',
  Plugins: 'Plugins',
  'Handy Shortcuts': 'Atalhos \u00FAteis',
  'Horizontal line': 'Linha horizontal',
  'Insert/edit image': 'Inserir/editar imagem',
  'Image description': 'Inserir descri\u00E7\u00E3o',
  Source: 'Endere\u00E7o da imagem',
  Dimensions: 'Dimens\u00F5es',
  'Constrain proportions': 'Manter propor\u00E7\u00F5es',
  General: 'Geral',
  Advanced: 'Avan\u00E7ado',
  Style: 'Estilo',
  'Vertical space': 'Espa\u00E7amento vertical',
  'Horizontal space': 'Espa\u00E7amento horizontal',
  Border: 'Borda',
  'Insert image': 'Inserir imagem',
  'Image...': 'Imagem...',
  'Image list': 'Lista de Imagens',
  'Rotate counterclockwise': 'Girar em sentido hor\u00E1rio',
  'Rotate clockwise': 'Girar em sentido anti-hor\u00E1rio',
  'Flip vertically': 'Virar verticalmente',
  'Flip horizontally': 'Virar horizontalmente',
  'Edit image': 'Editar imagem',
  'Image options': 'Op\u00E7\u00F5es de Imagem',
  'Zoom in': 'Aumentar zoom',
  'Zoom out': 'Diminuir zoom',
  Crop: 'Cortar',
  Resize: 'Redimensionar',
  Orientation: 'Orienta\u00E7\u00E3o',
  Brightness: 'Brilho',
  Sharpen: 'Aumentar nitidez',
  Contrast: 'Contraste',
  'Color levels': 'N\u00EDveis de cor',
  Gamma: 'Gama',
  Invert: 'Inverter',
  Apply: 'Aplicar',
  Back: 'Voltar',
  'Insert date/time': 'Inserir data/hora',
  'Date/time': 'data/hora',
  'Insert/Edit Link': 'Inserir/Editar Link',
  'Insert/edit link': 'Inserir/editar link',
  'Text to display': 'Texto para mostrar',
  Url: 'Url',
  'Open link in...': 'Abrir link em...',
  'Current window': 'Janela atual',
  None: 'Nenhum',
  'New window': 'Nova janela',
  'Remove link': 'Remover link',
  Anchors: '\u00C2ncoras',
  'Link...': 'Link...',
  'Paste or type a link': 'Cole ou digite um Link',
  'The URL you entered seems to be an email address. Do you want to add the required mailto: prefix?':
    'The URL you entered seems to be an email address. Do you want to add the required mailto: prefix?',
  'The URL you entered seems to be an external link. Do you want to add the required http:// prefix?':
    'A URL que voc\u00EA informou parece ser um link externo. Deseja incluir o prefixo http://?',
  'Link list': 'Lista de Links',
  'Insert video': 'Inserir v\u00EDdeo',
  'Insert/edit video': 'Inserir/editar v\u00EDdeo',
  'Insert/edit media': 'Inserir/editar imagem',
  'Alternative source': 'Fonte alternativa',
  'Alternative source URL': 'Endere\u00E7o URL alternativo',
  'Media poster (Image URL)': 'Post de m\u00EDdia (URL da Imagem)',
  'Paste your embed code below:':
    'Insira o c\u00F3digo de incorpora\u00E7\u00E3o abaixo:',
  Embed: 'Incorporar',
  'Media...': 'M\u00EDdia...',
  'Nonbreaking space': 'Espa\u00E7o n\u00E3o separ\u00E1vel',
  'Page break': 'Quebra de p\u00E1gina',
  'Paste as text': 'Colar como texto',
  Preview: 'Pr\u00E9-visualizar',
  'Print...': 'Imprimir...',
  Save: 'Salvar',
  Find: 'Localizar',
  'Replace with': 'Substituir por',
  Replace: 'Substituir',
  'Replace all': 'Substituir tudo',
  Previous: 'Anterior',
  Next: 'Pr\u00F3ximo',
  'Find and replace...': 'Encontrar e substituir...',
  'Could not find the specified string.':
    'N\u00E3o foi poss\u00EDvel encontrar o termo especificado',
  'Match case': 'Diferenciar mai\u00FAsculas e min\u00FAsculas',
  'Find whole words only': 'Encontrar somente palavras inteiras',
  'Spell check': 'Verifica\u00E7\u00E3o ortogr\u00E1fica',
  Ignore: 'Ignorar',
  'Ignore all': 'Ignorar tudo',
  Finish: 'Finalizar',
  'Add to Dictionary': 'Adicionar ao Dicion\u00E1rio',
  'Insert table': 'Inserir tabela',
  'Table properties': 'Propriedades da tabela',
  'Delete table': 'Excluir tabela',
  Cell: 'C\u00E9lula',
  Row: 'Linha',
  Column: 'Coluna',
  'Cell properties': 'Propriedades da c\u00E9lula',
  'Merge cells': 'Agrupar c\u00E9lulas',
  'Split cell': 'Dividir c\u00E9lula',
  'Insert row before': 'Inserir linha antes',
  'Insert row after': 'Inserir linha depois',
  'Delete row': 'Excluir linha',
  'Row properties': 'Propriedades da linha',
  'Cut row': 'Recortar linha',
  'Copy row': 'Copiar linha',
  'Paste row before': 'Colar linha antes',
  'Paste row after': 'Colar linha depois',
  'Insert column before': 'Inserir coluna antes',
  'Insert column after': 'Inserir coluna depois',
  'Delete column': 'Excluir coluna',
  Cols: 'Colunas',
  Rows: 'Linhas',
  Width: 'Largura',
  Height: 'Altura',
  'Cell spacing': 'Espa\u00E7amento da c\u00E9lula',
  'Cell padding': 'Espa\u00E7amento interno da c\u00E9lula',
  'Show caption': 'Mostrar descri\u00E7\u00E3o',
  Left: 'Esquerdo',
  Center: 'Centro',
  Right: 'Direita',
  'Cell type': 'Tipo de c\u00E9lula',
  Scope: 'Escopo',
  Alignment: 'Alinhamento',
  'H Align': 'Alinhamento H',
  'V Align': 'Alinhamento V',
  Top: 'Superior',
  Middle: 'Meio',
  Bottom: 'Inferior',
  'Header cell': 'C\u00E9lula cabe\u00E7alho',
  'Row group': 'Agrupar linha',
  'Column group': 'Agrupar coluna',
  'Row type': 'Tipo de linha',
  Header: 'Cabe\u00E7alho',
  Body: 'Corpo',
  Footer: 'Rodap\u00E9',
  'Border color': 'Cor da borda',
  'Insert template...': 'Inserir modelo...',
  Templates: 'Modelos',
  Template: 'Modelo',
  'Text color': 'Cor do texto',
  'Background color': 'Cor do fundo',
  'Custom...': 'Personalizado...',
  'Custom color': 'Cor personalizada',
  'No color': 'Nenhuma cor',
  'Remove color': 'Remover cor',
  'Table of Contents': '\u00EDndice de Conte\u00FAdo',
  'Show blocks': 'Mostrar blocos',
  'Show invisible characters': 'Exibir caracteres invis\u00EDveis',
  'Word count': 'Contador de palavras',
  Count: 'Contar',
  Document: 'Documento',
  Selection: 'Sele\u00E7\u00E3o',
  Words: 'Palavras',
  'Words: {0}': 'Palavras: {0}',
  '{0} words': '{0} palavras',
  File: 'Arquivo',
  Edit: 'Editar',
  Insert: 'Inserir',
  View: 'Visualizar',
  Format: 'Formatar',
  Table: 'Tabela',
  Tools: 'Ferramentas',
  'Powered by {0}': 'Distribu\u00EDdo por  {0}',
  'Rich Text Area. Press ALT-F9 for menu. Press ALT-F10 for toolbar. Press ALT-0 for help':
    '\u00C1rea de texto formatado. Pressione ALT-F9 para exibir o menu, ALT-F10 para exibir a barra de ferramentas ou ALT-0 para exibir a ajuda',
  'Image title': 'T\u00EDtulo da imagem',
  'Border width': 'Espessura da borda',
  'Border style': 'Estilo da borda',
  Error: 'Erro',
  Warn: 'Aviso',
  Valid: 'V\u00E1lido',
  'To open the popup, press Shift+Enter':
    'Para abrir a popup, aperte Shit+Enter',
  'Rich Text Area. Press ALT-0 for help.':
    '\u00C1rea Rich Text. Aperte ALT-0 para ajuda.',
  'System Font': 'Fonte do sistema',
  'Failed to upload image: {0}': 'Falha no upload da imagem: {0}',
  'Failed to load plugin: {0} from url {1}':
    'Falha ao carregar plugin: {0} da url {1}',
  'Failed to load plugin url: {0}': 'Falha ao carregar url do plugin: {0}',
  'Failed to initialize plugin: {0}': 'Falha ao inicializar plugin: {0}',
  example: 'exemplo',
  Search: 'Pesquisar',
  All: 'Tudo',
  Currency: 'Moeda',
  Text: 'Texto',
  Quotations: 'Cita\u00E7\u00F5es',
  Mathematical: 'Matem\u00E1tico',
  'Extended Latin': 'Latino estendido',
  Symbols: 'S\u00EDmbolos',
  Arrows: 'Setas',
  'User Defined': 'Definido pelo Usu\u00E1rio',
  'dollar sign': 's\u00EDmbolo de d\u00F3lar',
  'currency sign': 's\u00EDmbolo de moeda',
  'euro-currency sign': 's\u00EDmbolo de euro',
  'colon sign': 's\u00EDmbolo de dois pontos',
  'cruzeiro sign': 's\u00EDmbolo de cruzeiro',
  'french franc sign': 's\u00EDmbolo de franco franc\u00EAs',
  'lira sign': 's\u00EDmbolo de lira',
  'mill sign': 's\u00EDmbolo do mill',
  'naira sign': 's\u00EDmbolo da naira',
  'peseta sign': 's\u00EDmbolo da peseta',
  'rupee sign': 's\u00EDmbolo da r\u00FApia',
  'won sign': 's\u00EDmbolo do won',
  'new sheqel sign': 's\u00EDmbolo do novo sheqel',
  'dong sign': 's\u00EDmbolo do dong',
  'kip sign': 's\u00EDmbolo do kip',
  'tugrik sign': 's\u00EDmbolo do tugrik',
  'drachma sign': 's\u00EDmbolo do drachma',
  'german penny symbol': 's\u00EDmbolo de centavo alem\u00E3o',
  'peso sign': 's\u00EDmbolo do peso',
  'guarani sign': 's\u00EDmbolo do guarani',
  'austral sign': 's\u00EDmbolo do austral',
  'hryvnia sign': 's\u00EDmbolo do hryvnia',
  'cedi sign': 's\u00EDmbolo do cedi',
  'livre tournois sign': 's\u00EDmbolo do livre tournois',
  'spesmilo sign': 's\u00EDmbolo do spesmilo',
  'tenge sign': 's\u00EDmbolo do tenge',
  'indian rupee sign': 's\u00EDmbolo de r\u00FApia indiana',
  'turkish lira sign': 's\u00EDmbolo de lira turca',
  'nordic mark sign': 's\u00EDmbolo do marco n\u00F3rdico',
  'manat sign': 's\u00EDmbolo do manat',
  'ruble sign': 's\u00EDmbolo do rublo',
  'yen character': 'caractere do yen',
  'yuan character': 'caractere do yuan',
  'yuan character, in hong kong and taiwan':
    'caractere do yuan, em Hong Kong e Taiwan',
  'yen/yuan character variant one':
    'varia\u00E7\u00E3o do caractere de yen/yuan',
  'Loading emoticons...': 'Carregando emojis...',
  'Could not load emoticons': 'N\u00E3o foi poss\u00EDvel carregar emojis',
  People: 'Pessoas',
  'Animals and Nature': 'Animais e Natureza',
  'Food and Drink': 'Comida e Bebida',
  Activity: 'Atividade',
  'Travel and Places': 'Viagem e Lugares',
  Objects: 'Objetos',
  Flags: 'Bandeiras',
  Characters: 'Caracteres',
  'Characters (no spaces)': 'Caracteres (sem espa\u00E7os)',
  '{0} characters': '{0} caracteres',
  'Error: Form submit field collision.':
    'Erro: colis\u00E3o de bot\u00E3o de envio do formul\u00E1rio.',
  'Error: No form element found.':
    'Erro: elemento de formul\u00E1rio n\u00E3o encontrado.',
  Update: 'Atualizar',
  'Color swatch': 'Amostra de cor',
  Turquoise: 'Turquesa',
  Green: 'Verde',
  Blue: 'Azul',
  Purple: 'Roxo',
  'Navy Blue': 'Azul marinho',
  'Dark Turquoise': 'Turquesa escuro',
  'Dark Green': 'Verde escuro',
  'Medium Blue': 'Azul m\u00E9dio',
  'Medium Purple': 'Roxo m\u00E9dio',
  'Midnight Blue': 'Azul meia-noite',
  Yellow: 'Amarelo',
  Orange: 'Laranja',
  Red: 'Vermelho',
  'Light Gray': 'Cinza claro',
  Gray: 'Cinza',
  'Dark Yellow': 'Amarelo escuro',
  'Dark Orange': 'Laranja escuro',
  'Dark Red': 'Vermelho escuro',
  'Medium Gray': 'Cinza m\u00E9dio',
  'Dark Gray': 'Cinza escuro',
  'Light Green': 'Verde claro',
  'Light Yellow': 'Amarelo claro',
  'Light Red': 'Vermelho claro',
  'Light Purple': 'Roxo claro',
  'Light Blue': 'Azul claro',
  'Dark Purple': 'Roxo escuro',
  'Dark Blue': 'Azul escuro',
  Black: 'Preto',
  White: 'Branco',
  'Switch to or from fullscreen mode': 'Abrir ou fechar modo de tela cheia',
  'Open help dialog': 'Abrir janela de ajuda',
  history: 'hist\u00F3rico',
  styles: 'estilos',
  formatting: 'formata\u00E7\u00E3o',
  alignment: 'alinhamento',
  indentation: 'indenta\u00E7\u00E3o',
  'permanent pen': 'caneta permanente',
  comments: 'coment\u00E1rios',
  'Format Painter': 'Pincel de Formata\u00E7\u00E3o',
  'Insert/edit iframe': 'Inserir/editar iframe',
  Capitalization: 'Capitaliza\u00E7\u00E3o',
  lowercase: 'min\u00FAsculos',
  UPPERCASE: 'MAI\u00DASCULAS',
  'Title Case': 'T\u00EDtulo do caso',
  'Permanent Pen Properties': 'Propriedades da caneta permanente',
  'Permanent pen properties...': 'Propriedades de caneta permanentes...',
  Font: 'Fonte',
  Size: 'Tamanho',
  'More...': 'Mais...',
  'Spellcheck Language': 'Idioma de verifica\u00E7\u00E3o ortogr\u00E1fica',
  'Select...': 'Selecionar...',
  Preferences: 'Prefer\u00EAncias',
  Yes: 'Sim',
  No: 'N\u00E3o',
  'Keyboard Navigation': 'Navega\u00E7\u00E3o por Teclado',
  Version: 'Vers\u00E3o',
  Anchor: '\u00C2ncora',
  'Special character': 'Caracteres especiais',
  'Code sample': 'Exemplo de c\u00F3digo',
  Color: 'Cor',
  Emoticons: 'Emoticons',
  'Document properties': 'Propriedades do documento',
  Image: 'Imagem',
  'Insert link': 'Inserir link',
  Target: 'Alvo',
  Link: 'Link',
  Poster: 'Autor',
  Media: 'imagem',
  Print: 'Imprimir',
  Prev: 'Anterior',
  'Find and replace': 'Localizar e substituir',
  'Whole words': 'Palavras inteiras',
  Spellcheck: 'Corretor ortogr\u00E1fico',
  Caption: 'Legenda',
  'Insert template': 'Inserir modelo',
})
export default ptBR
