import React from "react";
import { NextSeo } from "next-seo";

import Header from "./Header";
import { Footer } from "./Footer";
import { Stack, Box } from "@chakra-ui/react";

type Props = {
  children: React.ReactNode;
  title: string;
  searchQuery?: string;
};
export default function DefaultLayout({ children, title, searchQuery }: Props) {
  return (
    <>
      <NextSeo
        title={title}
        openGraph={{
          type: "website",
        }}
      />
      {/*<Head>
         <title>{title} - Brasileis</title>
        <meta
          name="description"
          content="Generated by create next app"
          key="desc"
        />
        <meta
          property="og:description"
          content="And a social description for our cool page"
        />
        <meta
          property="og:image"
          content="https://example.com/images/cool-page.jpg"
        />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"
        />
        <meta name="robots" content="index, follow" />
        <meta name="googlebot" content="index, follow" />
        <meta name="google" content="notranslate" />

        <link rel="icon" href="/favicon.ico" />
      </Head>
       */}
      <Header searchQuery={searchQuery} />
      <Stack as="main" px={{ base: "0", sm: "4", md: "20" }} py={["0", "0", "12"]}>
        <Box mt={["0", "10", "10"]}>{children}</Box>
      </Stack>
      <Footer />
    </>
  );
}
