import React from "react";
import Head from "next/head";
import Header from "./Header";
import { Footer } from "./Footer";
import { Stack } from "@chakra-ui/react";

type Props = {
  children: React.ReactNode;
  title: string;
  searchQuery?: string;
};
export default function DefaultLayout({ children, title, searchQuery }: Props) {
  return (
    <>
      <Head>
        <title>{title} - Brasileis</title>
        <meta
          name="description"
          content="Generated by create next app"
          key="desc"
        />
        <meta
          property="og:description"
          content="And a social description for our cool page"
        />
        <meta
          property="og:image"
          content="https://example.com/images/cool-page.jpg"
        />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"
        />
        <meta name="robots" content="index, follow" />
        <meta name="googlebot" content="index, follow" />
        <meta name="google" content="notranslate" />

        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header searchQuery={searchQuery} />
      <Stack as="main" px={{ base: "4", sm: "4", md: "20" }} py="12">
        {children}
      </Stack>
      <Footer />
    </>
  );
}
